### ISSUE TITLE
When I include an icon, it doesn't install.

### ISSUE THREAD

**Issue by hoosteeno** [Osmose/refract#4]
If I leave icon field blank, it installs.

**Comment by Osmose** [comment]
Can you post the URL you're using for the icon when it fails?

**Comment by hoosteeno** [comment]
PNGs seem to work well. Not JPGs: http://www.cannedfood.co.uk/media/image/TwitterIcon.jpg

So maybe the bug is just adjusting language to "PNG Required". :)

**Comment by Osmose** [comment]
Since we use Pillow, it should handle most formats that matter, but my server didn't have libjpeg installed. It does now, so JPGs should work fine on refract.mkelly.me.

Thanks!
