### ISSUE TITLE
Feature request: Additional whitelist URLs?

### ISSUE THREAD

**Issue by hoosteeno** [Osmose/refract#5]
It would be sweet if I could build a "Google Docs" app that allowed URLs from both docs.google.com and drive.google.com, or *.google.com, or whatever. Fluidapp allows this. Not sure if it's possible but it would be great.

**Comment by Osmose** [comment]
What do you mean by whitelist? Unless there's something about open web apps that I'm unaware of we don't do any whitelisting.

**Comment by hoosteeno** [comment]
If you create an open web app for "https://docs.google.com"...
- It doesn't work. My SWAG for the reason is that some of the JS that makes it work comes from a different domain.
- If you click on the hamburger at top left and choose "Drive", it will open that in your default browser, even though it's "part of this application" somehow. My SWAG for this is that Google Drive is at a different domain.

"Whitelist" is the word I use for the observed behavior: Some links in the open web app open in the open web app, and other links in the open web app open in the default browser. Some essential content for the open web app is downloaded; some is (apparently) not. Allowing me to figure out that breakage and make a whitelist could mitigate. But of course that depends on whether an open web app has this affordance.

**Comment by Osmose** [comment]
I can't replicate the first issue, the app itself works fine for me. There's no whitelisting of domains that an app does that the browser doesn't; AFAIK an open web app as installed by Firefox launches a separate instance of Firefox with a new profile made specifically for that app and loads up a single window with one tab and no chrome, so it should function nearly identically to how it does in Firefox itself, with a few small exceptions.

As for the second issue, I think it's out of our control, in that any links that open new windows/tabs open up in your default browser as opposed to another window of the app. I can't find anything on how to toggle this app-wide, and we have no control over the app's behavior itself.

Closing this as I can't replicate and wontfix. Feel free to reopen if you're still getting this issue and have some tips for reproducing. Thanks!
